// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxEgqZI1Qfs0AsIpd-o0k0RskfWN8_4SQ',
    appId: '1:823139512573:web:1004ae033a8c8b2e598e94',
    messagingSenderId: '823139512573',
    projectId: 'app-educ-center',
    authDomain: 'app-educ-center.firebaseapp.com',
    storageBucket: 'app-educ-center.firebasestorage.app',
    measurementId: 'G-2D1G5LNQ54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT0LrSvzoFjX1y5VyPm5VK_ySjLxjZF9o',
    appId: '1:823139512573:android:3ecfc479e8a4b529598e94',
    messagingSenderId: '823139512573',
    projectId: 'app-educ-center',
    storageBucket: 'app-educ-center.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOb8D3qPveYIQXom_RHxTuI9U1C3-vG_o',
    appId: '1:823139512573:ios:3dc820a8e08f92c5598e94',
    messagingSenderId: '823139512573',
    projectId: 'app-educ-center',
    storageBucket: 'app-educ-center.firebasestorage.app',
    iosBundleId: 'com.example.educacenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOb8D3qPveYIQXom_RHxTuI9U1C3-vG_o',
    appId: '1:823139512573:ios:3dc820a8e08f92c5598e94',
    messagingSenderId: '823139512573',
    projectId: 'app-educ-center',
    storageBucket: 'app-educ-center.firebasestorage.app',
    iosBundleId: 'com.example.educacenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxEgqZI1Qfs0AsIpd-o0k0RskfWN8_4SQ',
    appId: '1:823139512573:web:2be048f601f3f267598e94',
    messagingSenderId: '823139512573',
    projectId: 'app-educ-center',
    authDomain: 'app-educ-center.firebaseapp.com',
    storageBucket: 'app-educ-center.firebasestorage.app',
    measurementId: 'G-VHBL8MT8TC',
  );
}
